//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPRECRUITMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANNER
    {
        public int BANNER_ID { get; set; }
        public string BANNER_TITLE { get; set; }
        public string BANNER_LINK { get; set; }
        public Nullable<int> BANNER_STATUS { get; set; }
        public string IMAGE_URL { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
