//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPRECRUITMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.CVs = new HashSet<CV>();
        }
    
        public int CANDIDATE_ID { get; set; }
        public string CANDIDATE_NAME { get; set; }
        public Nullable<int> SEX { get; set; }
        public string PHONENUMBER { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public bool ISDELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CV> CVs { get; set; }
    }
}
