//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPRECRUITMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_USER_LOG
    {
        public int LOG_ID { get; set; }
        public string LOG_TYPE { get; set; }
        public string LOG_TEXT { get; set; }
        public string LOG_DATA { get; set; }
        public string IP_ADDRESS { get; set; }
        public string CLIENT_INFO { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
    }
}
