//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPRECRUITMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_FUNCT_ROLE
    {
        public int ID { get; set; }
        public int FUN_ID { get; set; }
        public int ROLE_ID { get; set; }
        public string ISACTIVE { get; set; }
        public string ISDELETED { get; set; }
    }
}
