//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPRECRUITMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_ROLES
    {
        public int ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public string ROLE_KEY { get; set; }
        public Nullable<byte> ORD { get; set; }
        public string ISACTIVE { get; set; }
        public string ISDELETED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
    }
}
