//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPRECRUITMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_FUNCTIONS
    {
        public int FUN_ID { get; set; }
        public string FUN_NAME { get; set; }
        public string URL { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string FUN_KEY { get; set; }
        public string FUN_LEVEL { get; set; }
        public string CSSCLASS { get; set; }
        public Nullable<int> ORD { get; set; }
        public string ISDISPLAY { get; set; }
        public string ISDELETED { get; set; }
    }
}
