//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPRECRUITMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV
    {
        public int CV_ID { get; set; }
        public Nullable<int> CANDIDATE_ID { get; set; }
        public Nullable<int> JOB_ID { get; set; }
        public bool ISDELETED { get; set; }
        public Nullable<int> CV_STATUS { get; set; }
        public string CV_LINK { get; set; }
        public string CV_UPLOAD { get; set; }
        public string CV_DESCRIPTION { get; set; }
        public Nullable<int> CV_LOCATION { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Job Job { get; set; }
    }
}
