//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPRECRUITMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.CVs = new HashSet<CV>();
            this.Job_Location = new HashSet<Job_Location>();
            this.JobPositions = new HashSet<JobPosition>();
        }
    
        public int JOB_ID { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public string JOB_NAME { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRED_DATE { get; set; }
        public string JOB_DECRIPTION { get; set; }
        public string IMAGE { get; set; }
        public bool ISDELETED { get; set; }
        public Nullable<int> VIEW_COUNT { get; set; }
        public Nullable<int> JOB_STATUS { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public Nullable<int> CV_APPLY_COUNT { get; set; }
        public Nullable<bool> ACTIVE_BANNER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CV> CVs { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Location> Job_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPosition> JobPositions { get; set; }
    }
}
