//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPRECRUITMENT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VNPAY_RECRUITMENTEntities : DbContext
    {
        public VNPAY_RECRUITMENTEntities()
            : base("name=VNPAY_RECRUITMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANNER> BANNERs { get; set; }
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<CMS_FUNCT_ROLE> CMS_FUNCT_ROLE { get; set; }
        public virtual DbSet<CMS_FUNCTIONS> CMS_FUNCTIONS { get; set; }
        public virtual DbSet<CMS_ROLES> CMS_ROLES { get; set; }
        public virtual DbSet<CMS_USER_LOG> CMS_USER_LOG { get; set; }
        public virtual DbSet<CMS_USERS> CMS_USERS { get; set; }
        public virtual DbSet<CV> CVs { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Job_Location> Job_Location { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<JobPosition> JobPositions { get; set; }
    
        public virtual int PROC_BANNER_DELETE_BYID(Nullable<int> p_BANNER_ID)
        {
            var p_BANNER_IDParameter = p_BANNER_ID.HasValue ?
                new ObjectParameter("P_BANNER_ID", p_BANNER_ID) :
                new ObjectParameter("P_BANNER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BANNER_DELETE_BYID", p_BANNER_IDParameter);
        }
    
        public virtual int PROC_BANNER_INSERT(string p_BANNER_TITLE, string p_BANNER_LINK, string p_IMAGE_URL, Nullable<int> p_BANNER_STATUS)
        {
            var p_BANNER_TITLEParameter = p_BANNER_TITLE != null ?
                new ObjectParameter("P_BANNER_TITLE", p_BANNER_TITLE) :
                new ObjectParameter("P_BANNER_TITLE", typeof(string));
    
            var p_BANNER_LINKParameter = p_BANNER_LINK != null ?
                new ObjectParameter("P_BANNER_LINK", p_BANNER_LINK) :
                new ObjectParameter("P_BANNER_LINK", typeof(string));
    
            var p_IMAGE_URLParameter = p_IMAGE_URL != null ?
                new ObjectParameter("P_IMAGE_URL", p_IMAGE_URL) :
                new ObjectParameter("P_IMAGE_URL", typeof(string));
    
            var p_BANNER_STATUSParameter = p_BANNER_STATUS.HasValue ?
                new ObjectParameter("P_BANNER_STATUS", p_BANNER_STATUS) :
                new ObjectParameter("P_BANNER_STATUS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BANNER_INSERT", p_BANNER_TITLEParameter, p_BANNER_LINKParameter, p_IMAGE_URLParameter, p_BANNER_STATUSParameter);
        }
    
        public virtual ObjectResult<PROC_BANNER_SELECT_BY_ID_Result> PROC_BANNER_SELECT_BY_ID(Nullable<int> p_BANNER_ID)
        {
            var p_BANNER_IDParameter = p_BANNER_ID.HasValue ?
                new ObjectParameter("P_BANNER_ID", p_BANNER_ID) :
                new ObjectParameter("P_BANNER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_BANNER_SELECT_BY_ID_Result>("PROC_BANNER_SELECT_BY_ID", p_BANNER_IDParameter);
        }
    
        public virtual ObjectResult<PROC_BANNER_SELECT_TO_PLAY_Result> PROC_BANNER_SELECT_TO_PLAY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_BANNER_SELECT_TO_PLAY_Result>("PROC_BANNER_SELECT_TO_PLAY");
        }
    
        public virtual ObjectResult<PROC_BANNER_SELECTALL_Result> PROC_BANNER_SELECTALL(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW, string p_KEYWORD, Nullable<int> p_STATUS)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            var p_KEYWORDParameter = p_KEYWORD != null ?
                new ObjectParameter("P_KEYWORD", p_KEYWORD) :
                new ObjectParameter("P_KEYWORD", typeof(string));
    
            var p_STATUSParameter = p_STATUS.HasValue ?
                new ObjectParameter("P_STATUS", p_STATUS) :
                new ObjectParameter("P_STATUS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_BANNER_SELECTALL_Result>("PROC_BANNER_SELECTALL", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW, p_KEYWORDParameter, p_STATUSParameter);
        }
    
        public virtual int PROC_BANNER_UPDATE(Nullable<int> p_BANNER_ID, string p_BANNER_TITLE, string p_BANNER_LINK, Nullable<int> p_BANNER_STATUS, string p_IMAGE_URL)
        {
            var p_BANNER_IDParameter = p_BANNER_ID.HasValue ?
                new ObjectParameter("P_BANNER_ID", p_BANNER_ID) :
                new ObjectParameter("P_BANNER_ID", typeof(int));
    
            var p_BANNER_TITLEParameter = p_BANNER_TITLE != null ?
                new ObjectParameter("P_BANNER_TITLE", p_BANNER_TITLE) :
                new ObjectParameter("P_BANNER_TITLE", typeof(string));
    
            var p_BANNER_LINKParameter = p_BANNER_LINK != null ?
                new ObjectParameter("P_BANNER_LINK", p_BANNER_LINK) :
                new ObjectParameter("P_BANNER_LINK", typeof(string));
    
            var p_BANNER_STATUSParameter = p_BANNER_STATUS.HasValue ?
                new ObjectParameter("P_BANNER_STATUS", p_BANNER_STATUS) :
                new ObjectParameter("P_BANNER_STATUS", typeof(int));
    
            var p_IMAGE_URLParameter = p_IMAGE_URL != null ?
                new ObjectParameter("P_IMAGE_URL", p_IMAGE_URL) :
                new ObjectParameter("P_IMAGE_URL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BANNER_UPDATE", p_BANNER_IDParameter, p_BANNER_TITLEParameter, p_BANNER_LINKParameter, p_BANNER_STATUSParameter, p_IMAGE_URLParameter);
        }
    
        public virtual int PROC_BANNER_UPDATE_WITHOUT_IMAGE(Nullable<int> p_BANNER_ID, string p_BANNER_TITLE, string p_BANNER_LINK, Nullable<int> p_BANNER_STATUS)
        {
            var p_BANNER_IDParameter = p_BANNER_ID.HasValue ?
                new ObjectParameter("P_BANNER_ID", p_BANNER_ID) :
                new ObjectParameter("P_BANNER_ID", typeof(int));
    
            var p_BANNER_TITLEParameter = p_BANNER_TITLE != null ?
                new ObjectParameter("P_BANNER_TITLE", p_BANNER_TITLE) :
                new ObjectParameter("P_BANNER_TITLE", typeof(string));
    
            var p_BANNER_LINKParameter = p_BANNER_LINK != null ?
                new ObjectParameter("P_BANNER_LINK", p_BANNER_LINK) :
                new ObjectParameter("P_BANNER_LINK", typeof(string));
    
            var p_BANNER_STATUSParameter = p_BANNER_STATUS.HasValue ?
                new ObjectParameter("P_BANNER_STATUS", p_BANNER_STATUS) :
                new ObjectParameter("P_BANNER_STATUS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BANNER_UPDATE_WITHOUT_IMAGE", p_BANNER_IDParameter, p_BANNER_TITLEParameter, p_BANNER_LINKParameter, p_BANNER_STATUSParameter);
        }
    
        public virtual int PROC_CANDIDATE_DELETEBYID(Nullable<int> p_CANDIDATE_ID)
        {
            var p_CANDIDATE_IDParameter = p_CANDIDATE_ID.HasValue ?
                new ObjectParameter("P_CANDIDATE_ID", p_CANDIDATE_ID) :
                new ObjectParameter("P_CANDIDATE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CANDIDATE_DELETEBYID", p_CANDIDATE_IDParameter);
        }
    
        public virtual int PROC_CANDIDATE_INSERT(string p_CANDIDATE_NAME, Nullable<int> p_SEX, string p_PHONENUMBER, string p_EMAIL)
        {
            var p_CANDIDATE_NAMEParameter = p_CANDIDATE_NAME != null ?
                new ObjectParameter("P_CANDIDATE_NAME", p_CANDIDATE_NAME) :
                new ObjectParameter("P_CANDIDATE_NAME", typeof(string));
    
            var p_SEXParameter = p_SEX.HasValue ?
                new ObjectParameter("P_SEX", p_SEX) :
                new ObjectParameter("P_SEX", typeof(int));
    
            var p_PHONENUMBERParameter = p_PHONENUMBER != null ?
                new ObjectParameter("P_PHONENUMBER", p_PHONENUMBER) :
                new ObjectParameter("P_PHONENUMBER", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CANDIDATE_INSERT", p_CANDIDATE_NAMEParameter, p_SEXParameter, p_PHONENUMBERParameter, p_EMAILParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PROC_CANDIDATE_SELECT_ID(string p_PHONENUMBER, string p_EMAIL)
        {
            var p_PHONENUMBERParameter = p_PHONENUMBER != null ?
                new ObjectParameter("P_PHONENUMBER", p_PHONENUMBER) :
                new ObjectParameter("P_PHONENUMBER", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PROC_CANDIDATE_SELECT_ID", p_PHONENUMBERParameter, p_EMAILParameter);
        }
    
        public virtual int PROC_CMS_ROLES_INSERT(string p_ROLE_NAME, string p_ROLE_KEY, Nullable<int> p_ORD, string p_ISACTIVE, string p_ISDELETED)
        {
            var p_ROLE_NAMEParameter = p_ROLE_NAME != null ?
                new ObjectParameter("P_ROLE_NAME", p_ROLE_NAME) :
                new ObjectParameter("P_ROLE_NAME", typeof(string));
    
            var p_ROLE_KEYParameter = p_ROLE_KEY != null ?
                new ObjectParameter("P_ROLE_KEY", p_ROLE_KEY) :
                new ObjectParameter("P_ROLE_KEY", typeof(string));
    
            var p_ORDParameter = p_ORD.HasValue ?
                new ObjectParameter("P_ORD", p_ORD) :
                new ObjectParameter("P_ORD", typeof(int));
    
            var p_ISACTIVEParameter = p_ISACTIVE != null ?
                new ObjectParameter("P_ISACTIVE", p_ISACTIVE) :
                new ObjectParameter("P_ISACTIVE", typeof(string));
    
            var p_ISDELETEDParameter = p_ISDELETED != null ?
                new ObjectParameter("P_ISDELETED", p_ISDELETED) :
                new ObjectParameter("P_ISDELETED", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CMS_ROLES_INSERT", p_ROLE_NAMEParameter, p_ROLE_KEYParameter, p_ORDParameter, p_ISACTIVEParameter, p_ISDELETEDParameter);
        }
    
        public virtual ObjectResult<PROC_CMS_ROLES_SELECTALL_Result> PROC_CMS_ROLES_SELECTALL(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CMS_ROLES_SELECTALL_Result>("PROC_CMS_ROLES_SELECTALL", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_CMS_ROLES_SELECTBYID_Result> PROC_CMS_ROLES_SELECTBYID(Nullable<int> p_ROLE_ID)
        {
            var p_ROLE_IDParameter = p_ROLE_ID.HasValue ?
                new ObjectParameter("P_ROLE_ID", p_ROLE_ID) :
                new ObjectParameter("P_ROLE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CMS_ROLES_SELECTBYID_Result>("PROC_CMS_ROLES_SELECTBYID", p_ROLE_IDParameter);
        }
    
        public virtual int PROC_CMS_ROLES_UPDATE(Nullable<int> p_ROLE_ID, string p_ROLE_NAME, string p_ROLE_KEY, Nullable<int> p_ORD, string p_ISACTIVE, string p_ISDELETED)
        {
            var p_ROLE_IDParameter = p_ROLE_ID.HasValue ?
                new ObjectParameter("P_ROLE_ID", p_ROLE_ID) :
                new ObjectParameter("P_ROLE_ID", typeof(int));
    
            var p_ROLE_NAMEParameter = p_ROLE_NAME != null ?
                new ObjectParameter("P_ROLE_NAME", p_ROLE_NAME) :
                new ObjectParameter("P_ROLE_NAME", typeof(string));
    
            var p_ROLE_KEYParameter = p_ROLE_KEY != null ?
                new ObjectParameter("P_ROLE_KEY", p_ROLE_KEY) :
                new ObjectParameter("P_ROLE_KEY", typeof(string));
    
            var p_ORDParameter = p_ORD.HasValue ?
                new ObjectParameter("P_ORD", p_ORD) :
                new ObjectParameter("P_ORD", typeof(int));
    
            var p_ISACTIVEParameter = p_ISACTIVE != null ?
                new ObjectParameter("P_ISACTIVE", p_ISACTIVE) :
                new ObjectParameter("P_ISACTIVE", typeof(string));
    
            var p_ISDELETEDParameter = p_ISDELETED != null ?
                new ObjectParameter("P_ISDELETED", p_ISDELETED) :
                new ObjectParameter("P_ISDELETED", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CMS_ROLES_UPDATE", p_ROLE_IDParameter, p_ROLE_NAMEParameter, p_ROLE_KEYParameter, p_ORDParameter, p_ISACTIVEParameter, p_ISDELETEDParameter);
        }
    
        public virtual ObjectResult<PROC_CMS_USER_LOGIN_Result> PROC_CMS_USER_LOGIN(string p_username, string p_password)
        {
            var p_usernameParameter = p_username != null ?
                new ObjectParameter("p_username", p_username) :
                new ObjectParameter("p_username", typeof(string));
    
            var p_passwordParameter = p_password != null ?
                new ObjectParameter("p_password", p_password) :
                new ObjectParameter("p_password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CMS_USER_LOGIN_Result>("PROC_CMS_USER_LOGIN", p_usernameParameter, p_passwordParameter);
        }
    
        public virtual int PROC_CMS_USERS_INSERT(string p_USERNAME, string p_EMAIL, string p_FIRSTNAME, string p_LASTNAME, string p_FULLNAME, string p_PASSWORD, string p_ISAPPROVED, string p_ISLOCKEDOUT, string p_CREATEDBY, Nullable<int> p_ROLE_ID)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_FIRSTNAMEParameter = p_FIRSTNAME != null ?
                new ObjectParameter("P_FIRSTNAME", p_FIRSTNAME) :
                new ObjectParameter("P_FIRSTNAME", typeof(string));
    
            var p_LASTNAMEParameter = p_LASTNAME != null ?
                new ObjectParameter("P_LASTNAME", p_LASTNAME) :
                new ObjectParameter("P_LASTNAME", typeof(string));
    
            var p_FULLNAMEParameter = p_FULLNAME != null ?
                new ObjectParameter("P_FULLNAME", p_FULLNAME) :
                new ObjectParameter("P_FULLNAME", typeof(string));
    
            var p_PASSWORDParameter = p_PASSWORD != null ?
                new ObjectParameter("P_PASSWORD", p_PASSWORD) :
                new ObjectParameter("P_PASSWORD", typeof(string));
    
            var p_ISAPPROVEDParameter = p_ISAPPROVED != null ?
                new ObjectParameter("P_ISAPPROVED", p_ISAPPROVED) :
                new ObjectParameter("P_ISAPPROVED", typeof(string));
    
            var p_ISLOCKEDOUTParameter = p_ISLOCKEDOUT != null ?
                new ObjectParameter("P_ISLOCKEDOUT", p_ISLOCKEDOUT) :
                new ObjectParameter("P_ISLOCKEDOUT", typeof(string));
    
            var p_CREATEDBYParameter = p_CREATEDBY != null ?
                new ObjectParameter("P_CREATEDBY", p_CREATEDBY) :
                new ObjectParameter("P_CREATEDBY", typeof(string));
    
            var p_ROLE_IDParameter = p_ROLE_ID.HasValue ?
                new ObjectParameter("P_ROLE_ID", p_ROLE_ID) :
                new ObjectParameter("P_ROLE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CMS_USERS_INSERT", p_USERNAMEParameter, p_EMAILParameter, p_FIRSTNAMEParameter, p_LASTNAMEParameter, p_FULLNAMEParameter, p_PASSWORDParameter, p_ISAPPROVEDParameter, p_ISLOCKEDOUTParameter, p_CREATEDBYParameter, p_ROLE_IDParameter);
        }
    
        public virtual ObjectResult<PROC_CMS_USERS_SEARCH_Result> PROC_CMS_USERS_SEARCH(string p_USERNAME, Nullable<int> p_ROLEID, Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            var p_ROLEIDParameter = p_ROLEID.HasValue ?
                new ObjectParameter("P_ROLEID", p_ROLEID) :
                new ObjectParameter("P_ROLEID", typeof(int));
    
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CMS_USERS_SEARCH_Result>("PROC_CMS_USERS_SEARCH", p_USERNAMEParameter, p_ROLEIDParameter, p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_CMS_USERS_SELECTALL_Result> PROC_CMS_USERS_SELECTALL(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CMS_USERS_SELECTALL_Result>("PROC_CMS_USERS_SELECTALL", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_CMS_USERS_SELECTBYID_Result> PROC_CMS_USERS_SELECTBYID(Nullable<int> p_USER_ID)
        {
            var p_USER_IDParameter = p_USER_ID.HasValue ?
                new ObjectParameter("P_USER_ID", p_USER_ID) :
                new ObjectParameter("P_USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CMS_USERS_SELECTBYID_Result>("PROC_CMS_USERS_SELECTBYID", p_USER_IDParameter);
        }
    
        public virtual int PROC_CMS_USERS_UPDATE(Nullable<int> p_USER_ID, string p_USERNAME, string p_EMAIL, string p_FULLNAME, string p_ISLOCKEDOUT, Nullable<int> p_ROLE_ID)
        {
            var p_USER_IDParameter = p_USER_ID.HasValue ?
                new ObjectParameter("P_USER_ID", p_USER_ID) :
                new ObjectParameter("P_USER_ID", typeof(int));
    
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_FULLNAMEParameter = p_FULLNAME != null ?
                new ObjectParameter("P_FULLNAME", p_FULLNAME) :
                new ObjectParameter("P_FULLNAME", typeof(string));
    
            var p_ISLOCKEDOUTParameter = p_ISLOCKEDOUT != null ?
                new ObjectParameter("P_ISLOCKEDOUT", p_ISLOCKEDOUT) :
                new ObjectParameter("P_ISLOCKEDOUT", typeof(string));
    
            var p_ROLE_IDParameter = p_ROLE_ID.HasValue ?
                new ObjectParameter("P_ROLE_ID", p_ROLE_ID) :
                new ObjectParameter("P_ROLE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CMS_USERS_UPDATE", p_USER_IDParameter, p_USERNAMEParameter, p_EMAILParameter, p_FULLNAMEParameter, p_ISLOCKEDOUTParameter, p_ROLE_IDParameter);
        }
    
        public virtual int PROC_CMS_USERS_UPDATE_PASS(Nullable<int> p_USER_ID, string p_PASSWORD)
        {
            var p_USER_IDParameter = p_USER_ID.HasValue ?
                new ObjectParameter("P_USER_ID", p_USER_ID) :
                new ObjectParameter("P_USER_ID", typeof(int));
    
            var p_PASSWORDParameter = p_PASSWORD != null ?
                new ObjectParameter("P_PASSWORD", p_PASSWORD) :
                new ObjectParameter("P_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CMS_USERS_UPDATE_PASS", p_USER_IDParameter, p_PASSWORDParameter);
        }
    
        public virtual int PROC_CV_DELETEBYID(Nullable<int> p_CV_ID)
        {
            var p_CV_IDParameter = p_CV_ID.HasValue ?
                new ObjectParameter("P_CV_ID", p_CV_ID) :
                new ObjectParameter("P_CV_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CV_DELETEBYID", p_CV_IDParameter);
        }
    
        public virtual int PROC_CV_INSERT(Nullable<int> p_CANDIDATE_ID, Nullable<int> p_JOB_ID, string p_CV_LINK, string p_CV_UPLOAD, string p_CV_DESCRIPTION, Nullable<int> p_LOCATION_ID)
        {
            var p_CANDIDATE_IDParameter = p_CANDIDATE_ID.HasValue ?
                new ObjectParameter("P_CANDIDATE_ID", p_CANDIDATE_ID) :
                new ObjectParameter("P_CANDIDATE_ID", typeof(int));
    
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            var p_CV_LINKParameter = p_CV_LINK != null ?
                new ObjectParameter("P_CV_LINK", p_CV_LINK) :
                new ObjectParameter("P_CV_LINK", typeof(string));
    
            var p_CV_UPLOADParameter = p_CV_UPLOAD != null ?
                new ObjectParameter("P_CV_UPLOAD", p_CV_UPLOAD) :
                new ObjectParameter("P_CV_UPLOAD", typeof(string));
    
            var p_CV_DESCRIPTIONParameter = p_CV_DESCRIPTION != null ?
                new ObjectParameter("P_CV_DESCRIPTION", p_CV_DESCRIPTION) :
                new ObjectParameter("P_CV_DESCRIPTION", typeof(string));
    
            var p_LOCATION_IDParameter = p_LOCATION_ID.HasValue ?
                new ObjectParameter("P_LOCATION_ID", p_LOCATION_ID) :
                new ObjectParameter("P_LOCATION_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CV_INSERT", p_CANDIDATE_IDParameter, p_JOB_IDParameter, p_CV_LINKParameter, p_CV_UPLOADParameter, p_CV_DESCRIPTIONParameter, p_LOCATION_IDParameter);
        }
    
        public virtual ObjectResult<PROC_CV_SELECT_DASHBOARD_Result> PROC_CV_SELECT_DASHBOARD(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW, string p_CANDIDATE_NAME, Nullable<int> p_JOB_ID, Nullable<int> p_GROUP_ID)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            var p_CANDIDATE_NAMEParameter = p_CANDIDATE_NAME != null ?
                new ObjectParameter("P_CANDIDATE_NAME", p_CANDIDATE_NAME) :
                new ObjectParameter("P_CANDIDATE_NAME", typeof(string));
    
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CV_SELECT_DASHBOARD_Result>("PROC_CV_SELECT_DASHBOARD", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW, p_CANDIDATE_NAMEParameter, p_JOB_IDParameter, p_GROUP_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PROC_CV_SELECT_STATUS(Nullable<int> p_CV_ID)
        {
            var p_CV_IDParameter = p_CV_ID.HasValue ?
                new ObjectParameter("P_CV_ID", p_CV_ID) :
                new ObjectParameter("P_CV_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PROC_CV_SELECT_STATUS", p_CV_IDParameter);
        }
    
        public virtual ObjectResult<PROC_CV_SELECTALL_Result> PROC_CV_SELECTALL(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW, string p_CANDIDATE_NAME, Nullable<int> p_JOB_ID, Nullable<int> p_GROUP_ID, Nullable<int> p_STATUS)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            var p_CANDIDATE_NAMEParameter = p_CANDIDATE_NAME != null ?
                new ObjectParameter("P_CANDIDATE_NAME", p_CANDIDATE_NAME) :
                new ObjectParameter("P_CANDIDATE_NAME", typeof(string));
    
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            var p_STATUSParameter = p_STATUS.HasValue ?
                new ObjectParameter("P_STATUS", p_STATUS) :
                new ObjectParameter("P_STATUS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CV_SELECTALL_Result>("PROC_CV_SELECTALL", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW, p_CANDIDATE_NAMEParameter, p_JOB_IDParameter, p_GROUP_IDParameter, p_STATUSParameter);
        }
    
        public virtual ObjectResult<PROC_CV_SELECTBYID_Result> PROC_CV_SELECTBYID(Nullable<int> p_CV_ID)
        {
            var p_CV_IDParameter = p_CV_ID.HasValue ?
                new ObjectParameter("P_CV_ID", p_CV_ID) :
                new ObjectParameter("P_CV_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CV_SELECTBYID_Result>("PROC_CV_SELECTBYID", p_CV_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PROC_CV_UNREAD_COUNT(Nullable<int> p_JOB_ID)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PROC_CV_UNREAD_COUNT", p_JOB_IDParameter);
        }
    
        public virtual int PROC_CV_UPDATE(Nullable<int> p_CV_ID, Nullable<int> p_STATUS)
        {
            var p_CV_IDParameter = p_CV_ID.HasValue ?
                new ObjectParameter("P_CV_ID", p_CV_ID) :
                new ObjectParameter("P_CV_ID", typeof(int));
    
            var p_STATUSParameter = p_STATUS.HasValue ?
                new ObjectParameter("P_STATUS", p_STATUS) :
                new ObjectParameter("P_STATUS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CV_UPDATE", p_CV_IDParameter, p_STATUSParameter);
        }
    
        public virtual int PROC_GROUP_DELETEBYID(Nullable<int> p_GROUP_ID)
        {
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_GROUP_DELETEBYID", p_GROUP_IDParameter);
        }
    
        public virtual ObjectResult<PROC_GROUP_SELECTALL_Result> PROC_GROUP_SELECTALL(Nullable<int> p_PAGESIZE, string kEYWORD, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var kEYWORDParameter = kEYWORD != null ?
                new ObjectParameter("KEYWORD", kEYWORD) :
                new ObjectParameter("KEYWORD", typeof(string));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GROUP_SELECTALL_Result>("PROC_GROUP_SELECTALL", p_PAGESIZEParameter, kEYWORDParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_GROUP_SELECTBYID_Result> PROC_GROUP_SELECTBYID(Nullable<int> p_GROUP_ID)
        {
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GROUP_SELECTBYID_Result>("PROC_GROUP_SELECTBYID", p_GROUP_IDParameter);
        }
    
        public virtual int PROC_GROUPS_INSERT(string p_GROUP_NAME, string p_ISDELETED)
        {
            var p_GROUP_NAMEParameter = p_GROUP_NAME != null ?
                new ObjectParameter("P_GROUP_NAME", p_GROUP_NAME) :
                new ObjectParameter("P_GROUP_NAME", typeof(string));
    
            var p_ISDELETEDParameter = p_ISDELETED != null ?
                new ObjectParameter("P_ISDELETED", p_ISDELETED) :
                new ObjectParameter("P_ISDELETED", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_GROUPS_INSERT", p_GROUP_NAMEParameter, p_ISDELETEDParameter);
        }
    
        public virtual int PROC_GROUPS_UPDATE(Nullable<int> p_GROUP_ID, string p_GROUP_NAME)
        {
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            var p_GROUP_NAMEParameter = p_GROUP_NAME != null ?
                new ObjectParameter("P_GROUP_NAME", p_GROUP_NAME) :
                new ObjectParameter("P_GROUP_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_GROUPS_UPDATE", p_GROUP_IDParameter, p_GROUP_NAMEParameter);
        }
    
        public virtual ObjectResult<PROC_JOB_ACTIVE_BANNER_FRONTEND_Result> PROC_JOB_ACTIVE_BANNER_FRONTEND()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_ACTIVE_BANNER_FRONTEND_Result>("PROC_JOB_ACTIVE_BANNER_FRONTEND");
        }
    
        public virtual ObjectResult<Nullable<int>> PROC_JOB_COUNT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PROC_JOB_COUNT");
        }
    
        public virtual int PROC_JOB_CV_APPLY_UPDATE(Nullable<int> p_JOB_ID)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_JOB_CV_APPLY_UPDATE", p_JOB_IDParameter);
        }
    
        public virtual int PROC_JOB_DELETEBYID(Nullable<int> p_JOB_ID)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_JOB_DELETEBYID", p_JOB_IDParameter);
        }
    
        public virtual int PROC_JOB_INSERT(Nullable<int> p_GROUP_ID, string p_JOB_NAME, Nullable<int> p_NUMBER, Nullable<decimal> p_SALARY, Nullable<System.DateTime> p_CREATED_DATE, Nullable<System.DateTime> p_EXPIRED_DATE, string p_JOB_DECRIPTION, string p_IMAGE, Nullable<int> p_JOB_STATUS)
        {
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            var p_JOB_NAMEParameter = p_JOB_NAME != null ?
                new ObjectParameter("P_JOB_NAME", p_JOB_NAME) :
                new ObjectParameter("P_JOB_NAME", typeof(string));
    
            var p_NUMBERParameter = p_NUMBER.HasValue ?
                new ObjectParameter("P_NUMBER", p_NUMBER) :
                new ObjectParameter("P_NUMBER", typeof(int));
    
            var p_SALARYParameter = p_SALARY.HasValue ?
                new ObjectParameter("P_SALARY", p_SALARY) :
                new ObjectParameter("P_SALARY", typeof(decimal));
    
            var p_CREATED_DATEParameter = p_CREATED_DATE.HasValue ?
                new ObjectParameter("P_CREATED_DATE", p_CREATED_DATE) :
                new ObjectParameter("P_CREATED_DATE", typeof(System.DateTime));
    
            var p_EXPIRED_DATEParameter = p_EXPIRED_DATE.HasValue ?
                new ObjectParameter("P_EXPIRED_DATE", p_EXPIRED_DATE) :
                new ObjectParameter("P_EXPIRED_DATE", typeof(System.DateTime));
    
            var p_JOB_DECRIPTIONParameter = p_JOB_DECRIPTION != null ?
                new ObjectParameter("P_JOB_DECRIPTION", p_JOB_DECRIPTION) :
                new ObjectParameter("P_JOB_DECRIPTION", typeof(string));
    
            var p_IMAGEParameter = p_IMAGE != null ?
                new ObjectParameter("P_IMAGE", p_IMAGE) :
                new ObjectParameter("P_IMAGE", typeof(string));
    
            var p_JOB_STATUSParameter = p_JOB_STATUS.HasValue ?
                new ObjectParameter("P_JOB_STATUS", p_JOB_STATUS) :
                new ObjectParameter("P_JOB_STATUS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_JOB_INSERT", p_GROUP_IDParameter, p_JOB_NAMEParameter, p_NUMBERParameter, p_SALARYParameter, p_CREATED_DATEParameter, p_EXPIRED_DATEParameter, p_JOB_DECRIPTIONParameter, p_IMAGEParameter, p_JOB_STATUSParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PROC_JOB_SEARCH_BY_NAME(string p_JOB_NAME, Nullable<int> p_GROUP_ID, Nullable<System.DateTime> p_CREATED_DATE, Nullable<int> p_NUMBER)
        {
            var p_JOB_NAMEParameter = p_JOB_NAME != null ?
                new ObjectParameter("P_JOB_NAME", p_JOB_NAME) :
                new ObjectParameter("P_JOB_NAME", typeof(string));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            var p_CREATED_DATEParameter = p_CREATED_DATE.HasValue ?
                new ObjectParameter("P_CREATED_DATE", p_CREATED_DATE) :
                new ObjectParameter("P_CREATED_DATE", typeof(System.DateTime));
    
            var p_NUMBERParameter = p_NUMBER.HasValue ?
                new ObjectParameter("P_NUMBER", p_NUMBER) :
                new ObjectParameter("P_NUMBER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PROC_JOB_SEARCH_BY_NAME", p_JOB_NAMEParameter, p_GROUP_IDParameter, p_CREATED_DATEParameter, p_NUMBERParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> PROC_JOB_SELECT_BYID_ACTIVE_BANNER(Nullable<int> p_JOB_ID)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("PROC_JOB_SELECT_BYID_ACTIVE_BANNER", p_JOB_IDParameter);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTALL_Result> PROC_JOB_SELECTALL(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW, string kEYWORD, Nullable<System.DateTime> p_CREATED_FROM, Nullable<System.DateTime> p_CREATED_TO, Nullable<int> p_STATUS, Nullable<int> p_GROUP_ID)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            var kEYWORDParameter = kEYWORD != null ?
                new ObjectParameter("KEYWORD", kEYWORD) :
                new ObjectParameter("KEYWORD", typeof(string));
    
            var p_CREATED_FROMParameter = p_CREATED_FROM.HasValue ?
                new ObjectParameter("P_CREATED_FROM", p_CREATED_FROM) :
                new ObjectParameter("P_CREATED_FROM", typeof(System.DateTime));
    
            var p_CREATED_TOParameter = p_CREATED_TO.HasValue ?
                new ObjectParameter("P_CREATED_TO", p_CREATED_TO) :
                new ObjectParameter("P_CREATED_TO", typeof(System.DateTime));
    
            var p_STATUSParameter = p_STATUS.HasValue ?
                new ObjectParameter("P_STATUS", p_STATUS) :
                new ObjectParameter("P_STATUS", typeof(int));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTALL_Result>("PROC_JOB_SELECTALL", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW, kEYWORDParameter, p_CREATED_FROMParameter, p_CREATED_TOParameter, p_STATUSParameter, p_GROUP_IDParameter);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTALL_BACKEND_Result> PROC_JOB_SELECTALL_BACKEND(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW, string kEYWORD, Nullable<System.DateTime> p_CREATED_FROM, Nullable<System.DateTime> p_CREATED_TO, Nullable<System.DateTime> p_EXPIRED_TO, Nullable<int> p_STATUS, Nullable<int> p_GROUP_ID)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            var kEYWORDParameter = kEYWORD != null ?
                new ObjectParameter("KEYWORD", kEYWORD) :
                new ObjectParameter("KEYWORD", typeof(string));
    
            var p_CREATED_FROMParameter = p_CREATED_FROM.HasValue ?
                new ObjectParameter("P_CREATED_FROM", p_CREATED_FROM) :
                new ObjectParameter("P_CREATED_FROM", typeof(System.DateTime));
    
            var p_CREATED_TOParameter = p_CREATED_TO.HasValue ?
                new ObjectParameter("P_CREATED_TO", p_CREATED_TO) :
                new ObjectParameter("P_CREATED_TO", typeof(System.DateTime));
    
            var p_EXPIRED_TOParameter = p_EXPIRED_TO.HasValue ?
                new ObjectParameter("P_EXPIRED_TO", p_EXPIRED_TO) :
                new ObjectParameter("P_EXPIRED_TO", typeof(System.DateTime));
    
            var p_STATUSParameter = p_STATUS.HasValue ?
                new ObjectParameter("P_STATUS", p_STATUS) :
                new ObjectParameter("P_STATUS", typeof(int));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTALL_BACKEND_Result>("PROC_JOB_SELECTALL_BACKEND", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW, kEYWORDParameter, p_CREATED_FROMParameter, p_CREATED_TOParameter, p_EXPIRED_TOParameter, p_STATUSParameter, p_GROUP_IDParameter);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTALL_BACKEND_DASHBOARD_Result> PROC_JOB_SELECTALL_BACKEND_DASHBOARD(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTALL_BACKEND_DASHBOARD_Result>("PROC_JOB_SELECTALL_BACKEND_DASHBOARD", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTALL_BACKEND_WITHOU_DATE_Result> PROC_JOB_SELECTALL_BACKEND_WITHOU_DATE(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW, string kEYWORD, Nullable<int> p_STATUS, Nullable<int> p_GROUP_ID)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            var kEYWORDParameter = kEYWORD != null ?
                new ObjectParameter("KEYWORD", kEYWORD) :
                new ObjectParameter("KEYWORD", typeof(string));
    
            var p_STATUSParameter = p_STATUS.HasValue ?
                new ObjectParameter("P_STATUS", p_STATUS) :
                new ObjectParameter("P_STATUS", typeof(int));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTALL_BACKEND_WITHOU_DATE_Result>("PROC_JOB_SELECTALL_BACKEND_WITHOU_DATE", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW, kEYWORDParameter, p_STATUSParameter, p_GROUP_IDParameter);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTALL_BANNER_Result> PROC_JOB_SELECTALL_BANNER(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTALL_BANNER_Result>("PROC_JOB_SELECTALL_BANNER", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTALL_BY_GROUP_Result> PROC_JOB_SELECTALL_BY_GROUP(Nullable<int> p_GROUP_ID)
        {
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTALL_BY_GROUP_Result>("PROC_JOB_SELECTALL_BY_GROUP", p_GROUP_IDParameter);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTALL_FRONTEND_Result> PROC_JOB_SELECTALL_FRONTEND(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW, string kEYWORD, Nullable<int> p_GROUP_ID)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            var kEYWORDParameter = kEYWORD != null ?
                new ObjectParameter("KEYWORD", kEYWORD) :
                new ObjectParameter("KEYWORD", typeof(string));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTALL_FRONTEND_Result>("PROC_JOB_SELECTALL_FRONTEND", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW, kEYWORDParameter, p_GROUP_IDParameter);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTALL_FRONTEND_FILTER_WITH_LOCATION_Result> PROC_JOB_SELECTALL_FRONTEND_FILTER_WITH_LOCATION(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW, string kEYWORD, Nullable<int> p_GROUP_ID, Nullable<int> p_LOCATION_ID)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            var kEYWORDParameter = kEYWORD != null ?
                new ObjectParameter("KEYWORD", kEYWORD) :
                new ObjectParameter("KEYWORD", typeof(string));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            var p_LOCATION_IDParameter = p_LOCATION_ID.HasValue ?
                new ObjectParameter("P_LOCATION_ID", p_LOCATION_ID) :
                new ObjectParameter("P_LOCATION_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTALL_FRONTEND_FILTER_WITH_LOCATION_Result>("PROC_JOB_SELECTALL_FRONTEND_FILTER_WITH_LOCATION", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW, kEYWORDParameter, p_GROUP_IDParameter, p_LOCATION_IDParameter);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTALL_SORTBY_JOB_NAME_Result> PROC_JOB_SELECTALL_SORTBY_JOB_NAME(Nullable<int> p_PAGESIZE, string kEYWORD, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var kEYWORDParameter = kEYWORD != null ?
                new ObjectParameter("KEYWORD", kEYWORD) :
                new ObjectParameter("KEYWORD", typeof(string));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTALL_SORTBY_JOB_NAME_Result>("PROC_JOB_SELECTALL_SORTBY_JOB_NAME", p_PAGESIZEParameter, kEYWORDParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTALL_WITH_LOCATION_Result> PROC_JOB_SELECTALL_WITH_LOCATION(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW, string kEYWORD, Nullable<System.DateTime> p_CREATED_FROM, Nullable<System.DateTime> p_CREATED_TO, Nullable<System.DateTime> p_EXPIRED_TO, Nullable<int> p_STATUS, Nullable<int> p_GROUP_ID, Nullable<int> p_LOCATION_ID)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            var kEYWORDParameter = kEYWORD != null ?
                new ObjectParameter("KEYWORD", kEYWORD) :
                new ObjectParameter("KEYWORD", typeof(string));
    
            var p_CREATED_FROMParameter = p_CREATED_FROM.HasValue ?
                new ObjectParameter("P_CREATED_FROM", p_CREATED_FROM) :
                new ObjectParameter("P_CREATED_FROM", typeof(System.DateTime));
    
            var p_CREATED_TOParameter = p_CREATED_TO.HasValue ?
                new ObjectParameter("P_CREATED_TO", p_CREATED_TO) :
                new ObjectParameter("P_CREATED_TO", typeof(System.DateTime));
    
            var p_EXPIRED_TOParameter = p_EXPIRED_TO.HasValue ?
                new ObjectParameter("P_EXPIRED_TO", p_EXPIRED_TO) :
                new ObjectParameter("P_EXPIRED_TO", typeof(System.DateTime));
    
            var p_STATUSParameter = p_STATUS.HasValue ?
                new ObjectParameter("P_STATUS", p_STATUS) :
                new ObjectParameter("P_STATUS", typeof(int));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            var p_LOCATION_IDParameter = p_LOCATION_ID.HasValue ?
                new ObjectParameter("P_LOCATION_ID", p_LOCATION_ID) :
                new ObjectParameter("P_LOCATION_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTALL_WITH_LOCATION_Result>("PROC_JOB_SELECTALL_WITH_LOCATION", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW, kEYWORDParameter, p_CREATED_FROMParameter, p_CREATED_TOParameter, p_EXPIRED_TOParameter, p_STATUSParameter, p_GROUP_IDParameter, p_LOCATION_IDParameter);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTALL_WITH_LOCATION_WITHOUT_DATE_Result> PROC_JOB_SELECTALL_WITH_LOCATION_WITHOUT_DATE(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW, string kEYWORD, Nullable<int> p_STATUS, Nullable<int> p_GROUP_ID, Nullable<int> p_LOCATION_ID)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            var kEYWORDParameter = kEYWORD != null ?
                new ObjectParameter("KEYWORD", kEYWORD) :
                new ObjectParameter("KEYWORD", typeof(string));
    
            var p_STATUSParameter = p_STATUS.HasValue ?
                new ObjectParameter("P_STATUS", p_STATUS) :
                new ObjectParameter("P_STATUS", typeof(int));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            var p_LOCATION_IDParameter = p_LOCATION_ID.HasValue ?
                new ObjectParameter("P_LOCATION_ID", p_LOCATION_ID) :
                new ObjectParameter("P_LOCATION_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTALL_WITH_LOCATION_WITHOUT_DATE_Result>("PROC_JOB_SELECTALL_WITH_LOCATION_WITHOUT_DATE", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW, kEYWORDParameter, p_STATUSParameter, p_GROUP_IDParameter, p_LOCATION_IDParameter);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTBY_CREATED_DATE_Result> PROC_JOB_SELECTBY_CREATED_DATE(Nullable<int> p_PAGESIZE, Nullable<System.DateTime> p_STARTED_DATE, Nullable<System.DateTime> p_END_DATE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_STARTED_DATEParameter = p_STARTED_DATE.HasValue ?
                new ObjectParameter("P_STARTED_DATE", p_STARTED_DATE) :
                new ObjectParameter("P_STARTED_DATE", typeof(System.DateTime));
    
            var p_END_DATEParameter = p_END_DATE.HasValue ?
                new ObjectParameter("P_END_DATE", p_END_DATE) :
                new ObjectParameter("P_END_DATE", typeof(System.DateTime));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTBY_CREATED_DATE_Result>("PROC_JOB_SELECTBY_CREATED_DATE", p_PAGESIZEParameter, p_STARTED_DATEParameter, p_END_DATEParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTBY_EXPIRED_DATE_Result> PROC_JOB_SELECTBY_EXPIRED_DATE(Nullable<int> p_PAGESIZE, Nullable<System.DateTime> p_STARTED_DATE, Nullable<System.DateTime> p_END_DATE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_STARTED_DATEParameter = p_STARTED_DATE.HasValue ?
                new ObjectParameter("P_STARTED_DATE", p_STARTED_DATE) :
                new ObjectParameter("P_STARTED_DATE", typeof(System.DateTime));
    
            var p_END_DATEParameter = p_END_DATE.HasValue ?
                new ObjectParameter("P_END_DATE", p_END_DATE) :
                new ObjectParameter("P_END_DATE", typeof(System.DateTime));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTBY_EXPIRED_DATE_Result>("PROC_JOB_SELECTBY_EXPIRED_DATE", p_PAGESIZEParameter, p_STARTED_DATEParameter, p_END_DATEParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTBY_GROUP_NAME_Result> PROC_JOB_SELECTBY_GROUP_NAME(Nullable<int> p_PAGESIZE, Nullable<int> p_GROUP_ID, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTBY_GROUP_NAME_Result>("PROC_JOB_SELECTBY_GROUP_NAME", p_PAGESIZEParameter, p_GROUP_IDParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTBY_JOB_NAME_Result> PROC_JOB_SELECTBY_JOB_NAME(Nullable<int> p_PAGESIZE, string p_JOB_NAME, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_JOB_NAMEParameter = p_JOB_NAME != null ?
                new ObjectParameter("P_JOB_NAME", p_JOB_NAME) :
                new ObjectParameter("P_JOB_NAME", typeof(string));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTBY_JOB_NAME_Result>("PROC_JOB_SELECTBY_JOB_NAME", p_PAGESIZEParameter, p_JOB_NAMEParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTBY_JOB_SALARY_HIGHER_Result> PROC_JOB_SELECTBY_JOB_SALARY_HIGHER(Nullable<int> p_PAGESIZE, Nullable<decimal> p_SALARY, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_SALARYParameter = p_SALARY.HasValue ?
                new ObjectParameter("P_SALARY", p_SALARY) :
                new ObjectParameter("P_SALARY", typeof(decimal));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTBY_JOB_SALARY_HIGHER_Result>("PROC_JOB_SELECTBY_JOB_SALARY_HIGHER", p_PAGESIZEParameter, p_SALARYParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTBY_JOB_SALARY_LOWER_Result> PROC_JOB_SELECTBY_JOB_SALARY_LOWER(Nullable<int> p_PAGESIZE, Nullable<decimal> p_SALARY, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_SALARYParameter = p_SALARY.HasValue ?
                new ObjectParameter("P_SALARY", p_SALARY) :
                new ObjectParameter("P_SALARY", typeof(decimal));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTBY_JOB_SALARY_LOWER_Result>("PROC_JOB_SELECTBY_JOB_SALARY_LOWER", p_PAGESIZEParameter, p_SALARYParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTBY_STATUS_Result> PROC_JOB_SELECTBY_STATUS(Nullable<int> p_PAGESIZE, Nullable<int> p_ISDELETED, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_ISDELETEDParameter = p_ISDELETED.HasValue ?
                new ObjectParameter("P_ISDELETED", p_ISDELETED) :
                new ObjectParameter("P_ISDELETED", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTBY_STATUS_Result>("PROC_JOB_SELECTBY_STATUS", p_PAGESIZEParameter, p_ISDELETEDParameter, p_PAGENOParameter, p_TOTALROW);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTBYID_Result> PROC_JOB_SELECTBYID(Nullable<int> p_JOB_ID)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTBYID_Result>("PROC_JOB_SELECTBYID", p_JOB_IDParameter);
        }
    
        public virtual ObjectResult<PROC_JOB_SELECTBYID_BACKEND_Result> PROC_JOB_SELECTBYID_BACKEND(Nullable<int> p_JOB_ID)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_JOB_SELECTBYID_BACKEND_Result>("PROC_JOB_SELECTBYID_BACKEND", p_JOB_IDParameter);
        }
    
        public virtual int PROC_JOB_SET_BANNER(Nullable<int> p_JOB_ID, Nullable<int> p_ACTIVE)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            var p_ACTIVEParameter = p_ACTIVE.HasValue ?
                new ObjectParameter("P_ACTIVE", p_ACTIVE) :
                new ObjectParameter("P_ACTIVE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_JOB_SET_BANNER", p_JOB_IDParameter, p_ACTIVEParameter);
        }
    
        public virtual int PROC_Job_UPDATE(Nullable<int> p_JOB_ID, Nullable<int> p_GROUP_ID, string p_JOB_NAME, Nullable<int> p_NUMBER, Nullable<decimal> p_SALARY, Nullable<System.DateTime> p_EXPIRED_DATE, string p_JOB_DECRIPTION, Nullable<int> p_STATUS, string p_IMAGE)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            var p_JOB_NAMEParameter = p_JOB_NAME != null ?
                new ObjectParameter("P_JOB_NAME", p_JOB_NAME) :
                new ObjectParameter("P_JOB_NAME", typeof(string));
    
            var p_NUMBERParameter = p_NUMBER.HasValue ?
                new ObjectParameter("P_NUMBER", p_NUMBER) :
                new ObjectParameter("P_NUMBER", typeof(int));
    
            var p_SALARYParameter = p_SALARY.HasValue ?
                new ObjectParameter("P_SALARY", p_SALARY) :
                new ObjectParameter("P_SALARY", typeof(decimal));
    
            var p_EXPIRED_DATEParameter = p_EXPIRED_DATE.HasValue ?
                new ObjectParameter("P_EXPIRED_DATE", p_EXPIRED_DATE) :
                new ObjectParameter("P_EXPIRED_DATE", typeof(System.DateTime));
    
            var p_JOB_DECRIPTIONParameter = p_JOB_DECRIPTION != null ?
                new ObjectParameter("P_JOB_DECRIPTION", p_JOB_DECRIPTION) :
                new ObjectParameter("P_JOB_DECRIPTION", typeof(string));
    
            var p_STATUSParameter = p_STATUS.HasValue ?
                new ObjectParameter("P_STATUS", p_STATUS) :
                new ObjectParameter("P_STATUS", typeof(int));
    
            var p_IMAGEParameter = p_IMAGE != null ?
                new ObjectParameter("P_IMAGE", p_IMAGE) :
                new ObjectParameter("P_IMAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_Job_UPDATE", p_JOB_IDParameter, p_GROUP_IDParameter, p_JOB_NAMEParameter, p_NUMBERParameter, p_SALARYParameter, p_EXPIRED_DATEParameter, p_JOB_DECRIPTIONParameter, p_STATUSParameter, p_IMAGEParameter);
        }
    
        public virtual int PROC_Job_UPDATE123(Nullable<int> p_JOB_ID, string p_JOB_NAME, Nullable<int> p_NUMBER, Nullable<decimal> p_SALARY, Nullable<System.DateTime> p_EXPIRED_DATE, string p_JOB_DECRIPTION, Nullable<int> p_STATUS, string p_IMAGE)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            var p_JOB_NAMEParameter = p_JOB_NAME != null ?
                new ObjectParameter("P_JOB_NAME", p_JOB_NAME) :
                new ObjectParameter("P_JOB_NAME", typeof(string));
    
            var p_NUMBERParameter = p_NUMBER.HasValue ?
                new ObjectParameter("P_NUMBER", p_NUMBER) :
                new ObjectParameter("P_NUMBER", typeof(int));
    
            var p_SALARYParameter = p_SALARY.HasValue ?
                new ObjectParameter("P_SALARY", p_SALARY) :
                new ObjectParameter("P_SALARY", typeof(decimal));
    
            var p_EXPIRED_DATEParameter = p_EXPIRED_DATE.HasValue ?
                new ObjectParameter("P_EXPIRED_DATE", p_EXPIRED_DATE) :
                new ObjectParameter("P_EXPIRED_DATE", typeof(System.DateTime));
    
            var p_JOB_DECRIPTIONParameter = p_JOB_DECRIPTION != null ?
                new ObjectParameter("P_JOB_DECRIPTION", p_JOB_DECRIPTION) :
                new ObjectParameter("P_JOB_DECRIPTION", typeof(string));
    
            var p_STATUSParameter = p_STATUS.HasValue ?
                new ObjectParameter("P_STATUS", p_STATUS) :
                new ObjectParameter("P_STATUS", typeof(int));
    
            var p_IMAGEParameter = p_IMAGE != null ?
                new ObjectParameter("P_IMAGE", p_IMAGE) :
                new ObjectParameter("P_IMAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_Job_UPDATE123", p_JOB_IDParameter, p_JOB_NAMEParameter, p_NUMBERParameter, p_SALARYParameter, p_EXPIRED_DATEParameter, p_JOB_DECRIPTIONParameter, p_STATUSParameter, p_IMAGEParameter);
        }
    
        public virtual int PROC_Job_VIEWCOUNT_UPDATE(Nullable<int> p_JOB_ID)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_Job_VIEWCOUNT_UPDATE", p_JOB_IDParameter);
        }
    
        public virtual int PROC_LOCATION_ADD_NEW(string p_LOCATION_NAME)
        {
            var p_LOCATION_NAMEParameter = p_LOCATION_NAME != null ?
                new ObjectParameter("P_LOCATION_NAME", p_LOCATION_NAME) :
                new ObjectParameter("P_LOCATION_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_LOCATION_ADD_NEW", p_LOCATION_NAMEParameter);
        }
    
        public virtual int PROC_LOCATION_DELETE(Nullable<int> p_LOCATION_ID)
        {
            var p_LOCATION_IDParameter = p_LOCATION_ID.HasValue ?
                new ObjectParameter("P_LOCATION_ID", p_LOCATION_ID) :
                new ObjectParameter("P_LOCATION_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_LOCATION_DELETE", p_LOCATION_IDParameter);
        }
    
        public virtual int PROC_LOCATION_DELETEBYID(Nullable<int> p_JOB_ID)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_LOCATION_DELETEBYID", p_JOB_IDParameter);
        }
    
        public virtual int PROC_LOCATION_INSERT(Nullable<int> p_LOCATION_ID, Nullable<int> p_JOB_ID)
        {
            var p_LOCATION_IDParameter = p_LOCATION_ID.HasValue ?
                new ObjectParameter("P_LOCATION_ID", p_LOCATION_ID) :
                new ObjectParameter("P_LOCATION_ID", typeof(int));
    
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_LOCATION_INSERT", p_LOCATION_IDParameter, p_JOB_IDParameter);
        }
    
        public virtual ObjectResult<string> PROC_LOCATION_NAME_SELECTALL(Nullable<int> p_JOB_ID)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PROC_LOCATION_NAME_SELECTALL", p_JOB_IDParameter);
        }
    
        public virtual ObjectResult<PROC_LOCATION_NAME_SELECTALL123_Result> PROC_LOCATION_NAME_SELECTALL123(Nullable<int> p_JOB_ID)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_LOCATION_NAME_SELECTALL123_Result>("PROC_LOCATION_NAME_SELECTALL123", p_JOB_IDParameter);
        }
    
        public virtual ObjectResult<string> PROC_LOCATION_SELECT_NAME_ONLY(Nullable<int> p_LOCATION_ID)
        {
            var p_LOCATION_IDParameter = p_LOCATION_ID.HasValue ?
                new ObjectParameter("P_LOCATION_ID", p_LOCATION_ID) :
                new ObjectParameter("P_LOCATION_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PROC_LOCATION_SELECT_NAME_ONLY", p_LOCATION_IDParameter);
        }
    
        public virtual ObjectResult<PROC_LOCATION_SELECTALL_Result> PROC_LOCATION_SELECTALL(Nullable<int> p_PAGESIZE, Nullable<int> p_PAGENO, ObjectParameter p_TOTALROW, string p_LOCATION_NAME)
        {
            var p_PAGESIZEParameter = p_PAGESIZE.HasValue ?
                new ObjectParameter("P_PAGESIZE", p_PAGESIZE) :
                new ObjectParameter("P_PAGESIZE", typeof(int));
    
            var p_PAGENOParameter = p_PAGENO.HasValue ?
                new ObjectParameter("P_PAGENO", p_PAGENO) :
                new ObjectParameter("P_PAGENO", typeof(int));
    
            var p_LOCATION_NAMEParameter = p_LOCATION_NAME != null ?
                new ObjectParameter("P_LOCATION_NAME", p_LOCATION_NAME) :
                new ObjectParameter("P_LOCATION_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_LOCATION_SELECTALL_Result>("PROC_LOCATION_SELECTALL", p_PAGESIZEParameter, p_PAGENOParameter, p_TOTALROW, p_LOCATION_NAMEParameter);
        }
    
        public virtual int PROC_REFRESH_JOB(Nullable<int> p_JOB_ID)
        {
            var p_JOB_IDParameter = p_JOB_ID.HasValue ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_REFRESH_JOB", p_JOB_IDParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Nullable<int>> PROC_JOB_ACTIVE_BANNER_COUNT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PROC_JOB_ACTIVE_BANNER_COUNT");
        }
    }
}
